import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const finalizeWorkflowUrl = new URL('../../.github/workflows/finalize-production-cutover.yml', import.meta.url)
const finalizeRunnerUrl = new URL('./finalize-production-cutover-actions.mjs', import.meta.url)
const deployWorkflowUrl = new URL('../../.github/workflows/deploy-production.yml', import.meta.url)
const wranglerUrl = new URL('../../wrangler.jsonc', import.meta.url)

test('final production cutover is a separate explicit irreversible workflow', async () => {
  const workflow = await readFile(finalizeWorkflowUrl, 'utf8')
  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /login_verified:/)
  assert.match(workflow, /inventory_reviewed:/)
  assert.match(workflow, /finalization_confirmed:/)
  assert.match(workflow, /github\.ref == 'refs\/heads\/master'/)
  assert.match(workflow, /environment: production/)
  assert.match(workflow, /timeout-minutes:\s*15/)
  assert.match(workflow, /Record production D1 restore point/)
  assert.match(workflow, /production-auth-smoke\.mjs/)
  assert.match(workflow, /finalize-production-cutover-actions\.mjs/)
  assert.match(workflow, /CUTOVER_MANAGER_EMAIL:\s*\$\{\{ secrets\.CUTOVER_MANAGER_EMAIL \}\}/)
  assert.match(workflow, /PRODUCTION_AUTH_PHASE:\s*multi_company/)
})

test('final production cutover runner rechecks readiness and verifies user_only with PIN physically absent', async () => {
  const source = await readFile(finalizeRunnerUrl, 'utf8')
  assert.match(source, /connectProductionD1Rest/)
  assert.match(source, /runMultiCompanyProductionAdmin/)
  assert.match(source, /inspect-inventory/)
  assert.match(source, /check-ready/)
  assert.match(source, /finalize-legacy/)
  assert.match(source, /--login-verified/)
  assert.match(source, /--inventory-reviewed/)
  assert.match(source, /business_auth_state/)
  assert.match(source, /auth_credentials/)
  assert.match(source, /user_only/)
  assert.match(source, /PIN legado removido/)
  assert.doesNotMatch(source, /console\.log\([^\n]*(CUTOVER_MANAGER_EMAIL|email)/)
})

test('normal production deploy is permanently multi-company after cutover and cannot recreate PIN', async () => {
  const workflow = await readFile(deployWorkflowUrl, 'utf8')
  const config = JSON.parse(await readFile(wranglerUrl, 'utf8'))
  assert.doesNotMatch(workflow, /auth_phase:/)
  assert.doesNotMatch(workflow, /readiness_confirmed:/)
  assert.doesNotMatch(workflow, /- legacy|\n\s*- prepare/)
  assert.doesNotMatch(workflow, /Configure production PIN|generate-pin-hash|AMOR_PIN:/)
  assert.match(workflow, /PRODUCTION_AUTH_PHASE:\s*multi_company/)
  assert.match(workflow, /Validate production multi-company configuration/)
  assert.match(workflow, /backup_confirmed:/)
  assert.match(workflow, /production-auth-smoke\.mjs/)
  assert.equal(config.vars.AUTH_EMAIL_ENABLED, 'true')
  assert.equal(config.vars.AUTH_MULTI_COMPANY_ENABLED, 'true')
  assert.equal(config.vars.AUTH_MULTI_COMPANY_PREPARE_ENABLED, 'false')
  assert.equal(config.vars.AUTH_PUBLIC_ORIGIN, 'https://app.mesiva.com.br')
})
