import { useEffect, useState } from 'react'
import Button from '../../../../shared/ui/Button.jsx'

export default function CompanyMembersPanel({company,api,grants,disabled,onAction}) {
  const [state,setState]=useState({loading:true}),[retry,setRetry]=useState(0)
  useEffect(()=>{let live=true;const controller=new AbortController();setState({loading:true,owner:api});void api.listMemberships(company.id,{signal:controller.signal}).then(data=>{if(live)setState({owner:api,users:data.users||[],loading:false})}).catch(error=>{if(live)setState({owner:api,error:error.message,loading:false})});return()=>{live=false;controller.abort()}},[api,company.id,company.managementRevision,retry])
  const visible=state.owner===api?state:{loading:true}
  if(visible.loading)return <p role="status">Carregando pessoas e convites…</p>
  if(visible.error)return <div role="alert"><p>{visible.error}</p><Button onClick={()=>setRetry(v=>v+1)}>Tentar novamente</Button></div>
  return <section className="platform-card"><h2>Pessoas e convites</h2>{!visible.users?.length?<p>Nenhuma pessoa vinculada a uma conta.</p>:<div className="platform-member-list">{visible.users.map(user=><article key={user.id} className="platform-member-row"><div><h3>{user.displayName}</h3><p className="platform-muted">{user.email} · {user.roleName}</p><span className={`platform-badge ${user.active&&user.membershipState==='active'?'is-active':''}`}>{user.membershipState==='invited'?'Aguardando convite/aceitação':user.active?'Vínculo ativo':'Vínculo revogado'}</span>{user.invitation&&<p className="platform-muted">{({accepted:'Convite aceito',revoked:'Convite revogado',expired:'Convite expirado',pending:'Convite pendente'})[user.invitation.status]}</p>}{user.active&&!user.canRevoke&&company.lifecycleStatus!=='deleted'&&grants.has('platform.memberships.manage')&&<p className="platform-muted">Mantenha uma pessoa com permissão para gerenciar a equipe ou suspenda a empresa antes de revogar.</p>}</div>
      <div className="platform-member-actions">{grants.has('platform.memberships.manage')&&user.canRevoke&&<Button variant="secondary" disabled={disabled} onClick={()=>onAction({operation:'membership.revoke',userId:user.id,label:user.displayName})}>Revogar acesso</Button>}{grants.has('platform.memberships.manage')&&user.canReactivate&&<Button variant="secondary" disabled={disabled} onClick={()=>onAction({operation:'membership.reactivate',userId:user.id,label:user.displayName})}>{user.membershipState==='invited'?'Permitir novo convite':'Reativar vínculo'}</Button>}{grants.has('platform.invitations.resend')&&user.canResendInvitation&&<Button variant="secondary" disabled={disabled} onClick={()=>onAction({operation:'invitation.resend',invitationId:user.invitation.id,label:user.email})}>Reenviar convite</Button>}{grants.has('platform.invitations.cancel')&&user.canCancelInvitation&&<Button variant="secondary" disabled={disabled} onClick={()=>onAction({operation:'invitation.cancel',invitationId:user.invitation.id,label:user.email})}>Cancelar convite</Button>}</div>
    </article>)}</div>}</section>
}
